### ISSUE TITLE
File access

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/coraza-http-wasm#17]
https://github.com/traefik/traefik/issues/10739

**Comment by attrib** [comment]
Will this include the log path `SecDebugLog`?

**Comment by tiran133** [comment]
I'm using Traefik 3.2.0 I'm trying to load a file, and it does not seem to work.

Traefik static config
```yaml 
experimental:
  plugins:
    coraza-http-wasm-traefik:
      moduleName: "github.com/jcchavezs/coraza-http-wasm-traefik"
      version: "v0.2.2"
      settings:
        mounts:
          - /coraza
```
`/coraza` is mounted from the docker host into the Traefik container

Via volumes: 
``` yaml
    volumes:
      - ./coraza:/coraza
```
The folder `coraza` contains a file named `crs-setup.conf`

in the middleware, I'm trying to load the file

```yaml
http:
  middlewares:
    my-coraza-http-wasm-traefik:
      plugin:
        coraza-http-wasm-traefik:
          crsEnabled: true
          directives:
            - Include ./coraza/crs-setup.conf
```

I get following error 

```
Failed to initialize WAF: invalid WAF config from string: failed to readfile: open coraza/crs-setup.conf: file does not exist
```

If I try to load it via `- Include /coraza/crs-setup.conf` I get:

```
Failed to initialize WAF: invalid WAF config from string: failed to readfile: read /coraza/crs-setup.conf: invalid name
```

Any idea?

**Comment by jcchavezs** [comment]
@tiran133 try `Include crs-setup.conf`

**Comment by tiran133** [comment]
Unfortunately not.
Still getting 

```
Failed to initialize WAF: invalid WAF config from string: failed to readfile: open crs-setup.conf: file does not exist
```

Not sure what's going, but I tried all sorts of combinations to include the file, but it seems that the folder is not mounted.

**Comment by jcchavezs** [comment]
I see. This sounds more like a traefik issue.

José Carlos Chávez

**Comment by tiran133** [comment]
Well the implementation is here it looks ok to me, I guess, but I'm not a go expert so not sure.

https://github.com/juliens/traefik/blob/ac0c880b1ffbe7d888a67586397976856cd7fc34/pkg/plugins/middlewarewasm.go#L89

For now, I gave up, and I will use the example file `Include @crs-setup.conf.example` and overwrite/add everything I need 
through the middleware directives: key

**Comment by jcchavezs** [comment]
you are right. It might not be a traefik issue. Let me put up a fix.

José Carlos Chávez

**Comment by jcchavezs** [comment]
Done, check 0.3.0

**Comment by tiran133** [comment]
Great! Thank you for your fast reply!

Can you tag the traefik plugin too?
https://github.com/jcchavezs/coraza-http-wasm-traefik


EDIT:

Just compiled to locally and used the 'localPlugins' for traefik. Still getting the same error.

```
Failed to initialize WAF: invalid WAF config from string: failed to readfile: open crs-setup.conf: file does not exist
```

Any combination of mounts and what not, it will not work for me.

Thank you anyway!

**Comment by jcchavezs** [comment]
Done
https://github.com/jcchavezs/coraza-http-wasm-traefik/releases/tag/v0.3.0

José Carlos Chávez

**Comment by tiran133** [comment]
Thank you.

It is still not working for me. 😮‍💨

**Comment by jcchavezs** [comment]
I believe the problem comes from https://github.com/corazawaf/coraza/issues/1208. I am testing the fix.

**Comment by jcchavezs** [comment]
I reopened this issue because I could not find an easy fix for it. I suspect the failure comes from the mounting functionality provided by traefik. When I mount a folder e.g. `/etc/coraza/testdata` I am not able to access such folder. Creating a wasm function with

```go
package main

import httpwasm "github.com/http-wasm/http-wasm-guest-tinygo/handler"

func main() {
	readDir(httpwasm.Host, ".")
	readDir(httpwasm.Host, "/")
	readDir(httpwasm.Host, "./etc")
	readDir(httpwasm.Host, "/etc")
	readDir(httpwasm.Host, "/etc/my-file")
}

func readDir(host api.Host, dir string) {
	dirEntries, err := os.ReadDir(dir)
	if err == nil {
		host.Log(api.LogLevelError, "=> reading dir"+dir)
		for _, f := range dirEntries {
			host.Log(api.LogLevelError, "reading file"+f.Name())
		}
	} else {
		host.Log(api.LogLevelError, "error reading dir "+err.Error())
	}
}
```

Fails all the time `e2e_traefik_local-1  | 2024-11-13T14:49:22Z ERR github.com/traefik/traefik/v3/pkg/logs/wasm.go:31 > error reading dir open /etc/coraza/testdata: file does not exist`

Ping @juliens

**Comment by jcchavezs** [comment]
Traefik merged a fix for this https://github.com/traefik/traefik/pull/11321. Let's see when they cut a release.

**Comment by alukyanovCerbo** [comment]
I have the same issue. even with the latest version of traefik

**Comment by coderMohammed1** [comment]
any fix?

**Comment by ArthurGarnier** [comment]
Hi,
Looks like traefik/traefik#10829 should fix this by adding a mount path in the configuration, but I'm not able to make it work. 

My current config is :
``` yaml
experimental:
  plugins:
    coraza-http-wasm-traefik:
      moduleName: "github.com/jcchavezs/coraza-http-wasm-traefik"
      version: "v0.3.0"
      settings:
        mounts:
          - /etc/traefik/ # Probably not a good idea, but temporary for the test
```

And the plugin config is :

``` yaml
    default-waf:
      plugin:
        coraza-http-wasm-traefik:
          directives:
            - Include /etc/traefik/coraza.conf
```

Still raise an error "file not found". 

Someone found the solution for this ?
